### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by junland** [JohnPattersonConsulting/DuneBuggyEFI#1]
Hello, I was wondering if a License file could be added to your project. If you need some help on choosing a License please visit TL;DR Legal [here](https://tldrlegal.com/) or for a more guided explanation see [ChooseALicense](https://choosealicense.com/)

I know there's a comment within the source that says `You are free to modify and redistribute this code without restriction.` though it's not really a standard practice for licensing your code. Below are some helpful links for licensing your code:

* [Licensing a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)
* [Adding a license to a repository](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository)

If you want a license close to what you have, might I suggest the [`Unlicense`](https://tldrlegal.com/license/unlicense) or [`MIT`](https://tldrlegal.com/license/mit-license) licenses. Let me know if you have any questions.

_Disclaimer: I am not a lawyer by the way, just someone who advocates for the open source and free software ecosystem and just happened to come across your buggy YouTube videos. (Great work by the way.)_

**Comment by JohnPattersonConsulting** [comment]
Thank you, I have just added a license file! Best regards.
